config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'order_details/create'
  get 'order_details/show'
  get 'order_details/index'
  get 'bookings/create'
  get 'bookings/show'
  get 'bookings/index'
  get 'order_items/create'
  get 'orders/create'
  get 'orders/show'
  get 'orders/index'
  get 'cart_items/new'
  get 'carts/index'
  get 'carts/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'
  get 'pages/about'

  root 'pages#index'


  resources :order_details
  resources :order_items
  resources :bookings

  resources :carts do
    resources :order_details
    resources :order_items
    resources :bookings
  end

  resources :users do
    resources :service_offers
    resources :carts
    resources :cart_items
    resources :bookings
  end

  resources :service_offers do
    resources :cart_items
    resources :carts
    resources :users
  end

  resources :cart_items do
    resources :carts
    resources :users
    resources :service_offers
  end

  put 'cart_items/:id/add', to: 'cart_items#add', as: 'add'
  put 'cart_items/:id/remove', to: 'cart_items#remove', as: 'remove'
  put 'cart_items/:id/delete', to: 'cart_items#delete', as: 'delete'

  resources :service_types


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/cart_item.rb
# frozen_string_literal: true

# model for Cart Items
class CartItem < ApplicationRecord
  belongs_to :cart
  validates_associated :cart
  belongs_to :service_offer
  validates_associated :service_offer

  validates :quantity, presence: true
  validates :quantity, numericality: { only_integer: true }

  def add_one_item
    increment(:quantity)
    save
  end

  def remove_one_item
    decrement(:quantity)
    save
  end

  def delete_item
    destroy
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[cart_id created_at id id_value quantity service_offer_id updated_at]
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    @cart_items = CartItem.all
  end

  def add
    @cart_item = CartItem.find(params[:id])
    @cart_item.add_one_item
    @cart_item.cart.total += @cart_item.service_offer.service_offer_price
    @cart_item.cart.save
    redirect_back_or_to root_path
  end

  def remove
    @cart_item = CartItem.find(params[:id])
    @cart_item.remove_one_item
    @cart_item.cart.total -= @cart_item.service_offer.service_offer_price
    @cart_item.cart.save
    redirect_back_or_to root_path
  end

  def delete
    @cart_item = CartItem.find(params[:id])
    @cart_item.cart.total -= @cart_item.service_offer.service_offer_price * @cart_item.quantity
    @cart_item.cart.save
    @cart_item.delete_item
    redirect_back_or_to root_path
  end

  def create
    @service_offer = ServiceOffer.find(params[:cart_item][:id])
    @cart_item = CartItem.create!(cart_item_params)
    @cart_item.cart.total += @cart_item.service_offer.service_offer_price * @cart_item.quantity
    @cart_item.cart.save
    redirect_back_or_to root_path
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity, :cart_id, :service_offer_id)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_cart_item.html.erb
<div class="text-center flex mx-auto justify-center p-2">
    
    <%if cart_item.quantity < cart_item.service_offer.slot_availabilty%>
        <%=button_to "+", add_path(cart_item), method: :put, class: "bg-blue-500 rounded-full px-2 mx-1" %>
    <%end%>
    <span><%=cart_item.quantity%></span> 
    <%if cart_item.quantity > 1 %>
    <%=button_to "-", remove_path(cart_item), method: :put, class: "bg-blue-500 rounded-full px-2 mx-1"   %>
    <%else%>
    <%=button_to "-", delete_path(cart_item), method: :put, class: "bg-blue-500 rounded-full px-2 mx-1"   %>
    <%end%>
    <span><%=cart_item.service_offer.service_offer_name%></span>
    <%=button_to "Remove", delete_path(cart_item), method: :put, class: "bg-red-300 rounded-full px-2 mx-1"   %>  
</div>

app/views/cart_items/_form.html.erb
<%= form_with model: [ service_offer, service_offer.cart_items.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/cart_items/new.html.erb
<div>
  <h1 class="font-bold text-4xl">CartItems#new</h1>
  <p>Find me in app/views/cart_items/new.html.erb</p>
</div>