config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'order_details/create'
  get 'order_details/show'
  get 'order_details/index'
  get 'bookings/create'
  get 'bookings/show'
  get 'bookings/index'
  get 'order_items/create'
  get 'orders/create'
  get 'orders/show'
  get 'orders/index'
  get 'cart_items/new'
  get 'carts/index'
  get 'carts/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'
  get 'pages/about'

  root 'pages#index'


  resources :order_details
  resources :order_items
  resources :bookings

  resources :carts do
    resources :order_details
    resources :order_items
    resources :bookings
  end

  resources :users do
    resources :service_offers
    resources :carts
    resources :cart_items
    resources :bookings
  end

  resources :service_offers do
    resources :cart_items
    resources :carts
    resources :users
  end

  resources :cart_items do
    resources :carts
    resources :users
    resources :service_offers
  end

  put 'cart_items/:id/add', to: 'cart_items#add', as: 'add'
  put 'cart_items/:id/remove', to: 'cart_items#remove', as: 'remove'
  put 'cart_items/:id/delete', to: 'cart_items#delete', as: 'delete'

  resources :service_types


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :check_cart
  helper_method :breadcrumbs

  def breadcrumbs
    @breadcrumbs ||= []
  end

  def add_breadcrumb(name, path = nil)
    breadcrumbs << Breadcrumb.new(name, path)
  end

  def check_cart
    return unless user_signed_in?
    return if current_user.cart

    Cart.create!(
      user_id: current_user.id,
      total:   0
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_categories.html.erb
<div class="grid grid-flow-col justify-stretch">
    <%= render @service_types %>
</div>

app/views/application/_footer.html.erb
    <div class="flex justify-evenly">
        <ul>
            <li><b>Support</b></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
        <ul>
            <li><b>About</b></li>
            <li><%= link_to "Home", "/pages/index" %></li>
            <li><%= link_to "About", "/pages/about" %></li>
            <li></li>
        </ul>
        <ul>
            <li><b>Community</b></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
        <ul>
            <li><b>Providing/Requests</b></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </div>

<footer class="flex justify-evenly">
    <div class="flex space-x-4">
        <div>
            Terms
        </div>
        <div>
            Privacy
        </div>
        <div>
            Copywrong 2024
        </div>
    </div>
    <div class="flex space-x-4">
        <div>
            Twitter
        </div>
        <div>
            Instagram
        </div>
        <div>
            CAD $
        </div>
    </div>
</footer>

app/views/application/_header.html.erb
<header class="flex justify-evenly">
    <h1>AirDnD</h1> 
    <div class="text-center">
        <div class="flex justify-center">
            <div class="mx-2">
                <%= link_to "Providers", "/users/", class: "text-center no-underline"%>
            </div>
            <div class="mx-2">
                <%= link_to "Service Offers", "/service_offers/", class: "text-center no-underline"%>
            </div>
        </div>
        <% if local_assigns[:offer] %>
            <div class="mx-2 text-center">
                  <%= search_form_for @q do |f| %>
                      <%= f.label :service_offer_name_or_service_offer_notes_cont %> <br>
                      <%= f.search_field :service_offer_name_or_service_offer_notes_cont %>
                          
                      <%= f.label :service_type_id_eq, "Service Type" %>
                      <%= f.collection_select :service_type_id_eq, ServiceType.all, :id, :service_type_name, include_blank: true %>
  
                    <%= f.submit %>
                  <%end%>
            </div>
        <% elsif local_assigns[:provider]  %>
              <div class="mx-2 text-center">
                <%= search_form_for @q do |f| %>
                    <%= f.label :user_name_or_description_cont %> <br>
                    <%= f.search_field :user_name_or_description_cont %>
                    <%= f.submit %>
                <% end %>
            </div>
          <% end %>
    </div>
    <div>
      <div class="text-center">Welcome, <%=user_signed_in? ? current_user.user_name : "Guest"%></div>
      <div class="text-center flex space-x-4">
        <div class=" bg-gray-200 rounded-lg m-auto p-2">
          <% if user_signed_in? %>
            <div><%= link_to "Edit Account", edit_user_registration_path %></div>
            <div><%= link_to 'Sign Out', destroy_user_session_path, data: { "turbo-method": :delete } %></div>
          <% else %>
            <div><%= link_to 'Sign In', new_user_session_path %></div>
            <div><%= link_to 'Sign Up', new_user_registration_path %></div>
          <% end %>
        </div>

          <% if user_signed_in? %>
            <div class=" bg-gray-200 rounded-lg m-auto p-2">
              <div><%=link_to "Orders", order_details_path%> / <%=link_to "Bookings", bookings_path%></div>
              <details>
                <summary><%=current_user.user_name%>'s Cart</summary>
                <div class="z-50 fixed bg-gray-200 list-outside list-none">
                  <% if current_user.cart%>
                    <% if current_user.cart.cart_items.exists?%>
                      <%= render current_user.cart.cart_items%>
                      <div>Total before taxes: $<%=Money.from_cents(current_user.cart.total, "CAD")%></div>
                      <div><%=link_to "check out!", current_user.cart %></div>
                    <%else%>
                      <div>Empty Cart!</div>
                    <%end%>
                  <%end%>
                </div>
              </details>
            </div>
          <% end%>
          
      </div>
    </div> 
</header>

<%= render "application/categories"%>

<nav>
  <ul class="breadcrumbs flex space-x-4 list-none">
    <% breadcrumbs.each do |crumb| %>
     <li>
      <% if crumb.link? %>
        <%= link_to crumb.name, crumb.path, class: "breadcrumb-link" %>
      <% else %>
        <span class="breadcrumb-page">
          <%= crumb.name %>
        </span>
      <% end %>

      <% unless crumb == breadcrumbs.last %>
        <span class="breadcrumb-separator">/</span>
      <% end %>
     </li>
    <% end %>
  </ul>
</nav>